### ISSUE TITLE
Pre-launch checklist

### ISSUE THREAD

**Issue by danielfdsilva** [WorldBank-Transport/ram-frontend#1]
### Content

- [ ] All text free from spelling errors
- [ ] Page and content formatting appropriate on all pages
- [ ] Placeholder text removed
- [ ] All pages have content
- [x] Favicon retina-ready created and displays correctly [HELPER: [Favic-o-Matic](http://www.favicomatic.com/)]
- [x] Device icons created and display correctly (Apple touch, Windows tile, etc)
- [x] Footer includes copyright statement
- [x] 404 page exists and is informative

### SEO & Analytics

- [x] Page titles are descriptive and SEO friendly
- [ ] All page titles are unique
- [x] Meta data included and appropriate
- [ ] humans.txt is generated and added to the root of website [HELPER: [Humans TXT](http://humanstxt.org/)]
- [ ] Google Analytics and relevant analytics/tracking tools installed

### Social

- [x] Open Graph tags included across website and appropriate (including images where possible)
- [x] Twitter Cards tags included across website and appropriate (including image/video/audio where 
 possible)

### Markup

- [ ] HTML has passed validation
- [ ] CSS has passed validation
- [ ] Site links have been tested and resolve correctly
- [ ] JavaScript is error free and linted

### Accessibility

- [ ] ARIA Landmark Roles specified
- [ ] Semantic headings and structure used, attending to HTML5 outline specs [HELPER: [HTML5 Outliner](https://gsnedders.html5.org/outliner/)]
- [ ] Images use appropriate `alt` text
- [ ] Associated label for all form controls

### Rendering

- [ ] Displays & functions correctly in all the required browsers
- [ ] Displays & functions correctly on all the required resolutions and devices

### Functionality

- [ ] Empty and partial states are properly communicated
- [ ] Loading is shown when appropriate

### Optimization

- [ ] Images have been optimized [HELPER: [Compressor.io](https://compressor.io/)]
- [ ] CSS is minified and combined
- [ ] JavaScript is minified and combined
- [ ] Enable gzip compression
- [ ] Ensure only necessary fonts, weights and character sets are installed (or embedded if possible)
- [ ] Run Google speed test and optimise accordingly (record score and known issues)

### Post-launch

- [ ] Ensure site is visible to search engines
- [ ] Images, media and links reference live URL
- [ ] Webfonts integrated and working correctly on live site
- [ ] Analytics has been setup and integrated into website
